### ISSUE TITLE
raw Git repos list support 

### ISSUE THREAD

**Issue by alexkutsan** [AkashRajpurohit/git-sync#15]
### Describe the feature or enhancement

It would be very cool to have the ability to list down git repos with SSH/HTTPS credentials for backup, not sticking to specific platform

**Comment by AkashRajpurohit** [comment]
This seems to be a good addition, do you want to work on this?

**Comment by AkashRajpurohit** [comment]
Support for this has been added in [v0.12.0](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.12.0). Thanks for sharing this improvement idea.
