### ISSUE TITLE
Error while cloning repositories

### ISSUE THREAD

**Issue by aeonSolutions** [AkashRajpurohit/git-sync#29]
### Describe the Bug

see log below

### Steps to reproduce

executed the exe file 

### Relevant log output

```shell
{"level":"fatal","time":"2024-08-22T09:05:22.567+0100","message":"Error cloning repo aeonSolutions/AeonLabs-AeonLabs-HomeAutomation-Distributed-power_storage-Selectable-USB-DC-power-outlet: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:28\ngithub.com/AkashRajpurohit/git-sync/pkg/github.GitHubClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/github/github.go:51"}
```

### Which browser are you using? (if relevant)

no relevant

**Comment by AkashRajpurohit** [comment]
Seems like it is not able to clone the repository, can you check for few things

1. Is this a private repository?
2. Are you able to clone the repository directly using the git command?
3. Does the access token have correct permissions?

**Comment by aeonSolutions** [comment]
Is this a private repository? No. 
Are you able to clone the repository directly using the git command? Yes.
Does the access token have correct permissions? Yes

**Comment by AkashRajpurohit** [comment]
The current set of debug logs won't be helpful, can you download the [v0.8.2 version](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.8.2) and run the git-sync command again with [log level](https://github.com/AkashRajpurohit/git-sync/wiki/Commands-and-Flags#log-level) set to debug `--log-level=debug`

**Comment by aeonSolutions** [comment]
ok. so i did what you asked. here's output where the errors occur:

```
{"level":"info","time":"2024-08-23T07:55:10.831+0100","message":"Updating repo: aeonSolutions/-openScienceResearch-12bit-LCD-1.69-TFT-Smart-DAQ-Device-with-unique-data-fingerprint"}
{"level":"debug","time":"2024-08-23T07:55:11.014+0100","message":"Output: fatal: not a git repository: '\\aeonSolutions\\WebCoder-Multi-Platform-Framework\\WebCoder-Multi-Platform-Framework.git'\n\n"}
{"level":"fatal","time":"2024-08-23T07:55:11.017+0100","message":"Error updating repo aeonSolutions/WebCoder-Multi-Platform-Framework: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/runner/work/git-sync/git-sync/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/runner/work/git-sync/git-sync/pkg/sync/sync.go:39\ngithub.com/AkashRajpurohit/git-sync/pkg/github.GitHubClient.Sync.func1\n\t/home/runner/work/git-sync/git-sync/pkg/github/github.go:51"}
```

**Comment by AkashRajpurohit** [comment]
This is a Windows system, right? I never tested git-sync on Windows, so I might have to do it if I get a chance.
Meanwhile, can you share your config file (excluding the access token details)?

**Comment by aeonSolutions** [comment]
Yes. I'm running windows 11. 
My config file :

```
backup_dir: \
cron: ""
exclude_orgs: []
exclude_repos: []
include_forks: false
include_orgs: []
include_repos: []
include_wiki: true
platform: github
server:
    domain: github.com
    protocol: https
token: ""
username: ""
workspace: ""
```

**Comment by AkashRajpurohit** [comment]
Can you update the backup_dir to be a valid path on your file system and re-run the program once?

**Comment by aeonSolutions** [comment]
the backup path is not the issue. As it created folders and subfolder in the root of the disk drive

**Comment by AkashRajpurohit** [comment]
Can you navigate to this path `\\aeonSolutions\\WebCoder-Multi-Platform-Framework\\WebCoder-Multi-Platform-Framework.git` and do `git status` or `git log` to see what the output is?
Strange that from the logs it shows that it is not a git repository.

**Comment by aeonSolutions** [comment]
that repository is located here:
https://github.com/aeonSolutions/WebCoder-Multi-Platform-Framework

here's the output
![image](https://github.com/user-attachments/assets/dba4fb08-d11a-4c15-8f3d-b9900389adba)

**Comment by AkashRajpurohit** [comment]
Not this, the path specified in the log shows `\\aeonSolutions\\WebCoder-Multi-Platform-Framework\\WebCoder-Multi-Platform-Framework.git`, can you `cd` into this path and then type `git status` command.

**Comment by aeonSolutions** [comment]
here it is

![image](https://github.com/user-attachments/assets/dfbe7a3f-4404-4791-be04-0e45292f8398)

**Comment by AkashRajpurohit** [comment]
Yeah so git-sync is throwing back the same error seen here, what are the contents of this folder, if you do `ls -al` you can see the contents, is it a bare repository?

**Comment by aeonSolutions** [comment]
i did a git-sync again and now the error is on another repository
![image](https://github.com/user-attachments/assets/5226bd91-1f39-41ad-aa69-2c7a933a4164)

**Comment by aeonSolutions** [comment]
Here's the output of "dir /s"

```
D:\aeonSolutions\WebCoder-Multi-Platform-Framework>dir /s
 Volume in drive D is New Volume
 Volume Serial Number is D8FA-B0D9

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
08/23/2024  03:10 PM    <DIR>          WebCoder-Multi-Platform-Framework.git
               0 File(s)              0 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
08/23/2024  03:10 PM               260 config
08/23/2024  03:10 PM                73 description
08/23/2024  03:10 PM    <DIR>          hooks
08/23/2024  03:10 PM    <DIR>          info
08/23/2024  03:10 PM    <DIR>          objects
               2 File(s)            333 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git\hooks

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
08/23/2024  03:10 PM               478 applypatch-msg.sample
08/23/2024  03:10 PM               896 commit-msg.sample
08/23/2024  03:10 PM             4,726 fsmonitor-watchman.sample
08/23/2024  03:10 PM               189 post-update.sample
08/23/2024  03:10 PM               424 pre-applypatch.sample
08/23/2024  03:10 PM             1,649 pre-commit.sample
08/23/2024  03:10 PM               416 pre-merge-commit.sample
08/23/2024  03:10 PM             1,374 pre-push.sample
08/23/2024  03:10 PM             4,898 pre-rebase.sample
08/23/2024  03:10 PM               544 pre-receive.sample
08/23/2024  03:10 PM             1,492 prepare-commit-msg.sample
08/23/2024  03:10 PM             2,783 push-to-checkout.sample
08/23/2024  03:10 PM             2,308 sendemail-validate.sample
08/23/2024  03:10 PM             3,650 update.sample
              14 File(s)         25,827 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git\info

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
08/23/2024  03:10 PM               240 exclude
               1 File(s)            240 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git\objects

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
08/23/2024  03:10 PM    <DIR>          info
08/23/2024  03:10 PM    <DIR>          pack
               0 File(s)              0 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git\objects\info

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
               0 File(s)              0 bytes

 Directory of D:\aeonSolutions\WebCoder-Multi-Platform-Framework\WebCoder-Multi-Platform-Framework.git\objects\pack

08/23/2024  03:10 PM    <DIR>          .
08/23/2024  03:10 PM    <DIR>          ..
               0 File(s)              0 bytes

     Total Files Listed:
              17 File(s)         26,400 bytes
              20 Dir(s)  429,329,657,856 bytes free

D:\aeonSolutions\WebCoder-Multi-Platform-Framework>
```

**Comment by AkashRajpurohit** [comment]
> i did a git-sync again and now the error is on another repository ![image](https://private-user-images.githubusercontent.com/7936768/360956091-5226bd91-1f39-41ad-aa69-2c7a933a4164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjM3MjEsIm5iZiI6MTcyNDQyMzQyMSwicGF0aCI6Ii83OTM2NzY4LzM2MDk1NjA5MS01MjI2YmQ5MS0xZjM5LTQxYWQtYWE2OS0yYzdhOTMzYTQxNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQzMDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNiMDU1MTZjZjViMjg1MzU5NTI5NDYyYmJlYzFjYjQ3ZmNkNDRmZjJhMzliZjljMTc4NDUyMzhkNWIxYjg2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pv9kyo0lWyJN2DmOAsJ_HAOa96EvvjhkxHDRTxVF8P0)

Can you run this with `--log-level=debug` so we can get some additional logs about the error output.

**Comment by BuyMyMojo** [comment]
Running this on an Arch Linux system system and I got the same issue.

output with --log-level=debug:

```
{"level":"debug","time":"2024-11-06T21:04:53.554+1100","message":"Output: Cloning into bare repository '/run/media/buymymojo/ExternalLinuxHDD/git-sync/BuyMyMojo/RustDrop/RustDrop.git'...\nerror: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)\nerror: 13482 bytes of body are still expected\nfetch-pack: unexpected disconnect while reading sideband packet\nfatal: early EOF\nfatal: fetch-pack: invalid index-pack output\n\n"}
{"level":"fatal","time":"2024-11-06T21:04:53.554+1100","message":"Error cloning repo BuyMyMojo/RustDrop: exit status 128\n","stacktrace":"github.com/AkashRajpurohit/git-sync/pkg/logger.Fatalf\n\t/home/buymymojo/go/pkg/mod/github.com/!akash!rajpurohit/git-sync@v0.11.1/pkg/logger/logger.go:96\ngithub.com/AkashRajpurohit/git-sync/pkg/sync.CloneOrUpdateRepo\n\t/home/buymymojo/go/pkg/mod/github.com/!akash!rajpurohit/git-sync@v0.11.1/pkg/sync/sync.go:70\ngithub.com/AkashRajpurohit/git-sync/pkg/github.GitHubClient.Sync.func1\n\t/home/buymymojo/go/pkg/mod/github.com/!akash!rajpurohit/git-sync@v0.11.1/pkg/github/github.go:51"}
``` 

again it's on line 51 of github.go, I can re-run the command and it seems to happen on a different repo with each attempt.

seems like it could be some kind of rate limit cutting the connection on GitHub's end?

**Comment by AkashRajpurohit** [comment]
It can possibly be rate limiting, can you try creating a different token or try after sometime when the rate limit would have been reset.

**Comment by BuyMyMojo** [comment]
> It can possibly be rate limiting, can you try creating a different token or try after sometime when the rate limit would have been reset.

I have tried two tokens and attempted at different times so I think the stopping at different repos is the rate limit being tripped differently. maybe a small delay between repo pulls could fix this

**Comment by AkashRajpurohit** [comment]
As part of [v0.13.0](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.13.0) release, support for concurrency is added, so you can tweak it accordingly if you are getting rate limited.
Closing this issue for now but if you are still facing the issue then feel free to open a new issue.
