### ISSUE TITLE
Change in configuration filters

### ISSUE THREAD

**Issue by jbonadiman** [AkashRajpurohit/git-sync#3]
### Describe the feature or enhancement

I realized that if I have a lot of repos and I just want to sync some of them, that's pretty easy. I just list them in the repo list, as instructed.
But if otherwise, I want to sync all my repos except some of them, that's kinda harder. I need to instead list all the repos I want, this list could get pretty big and also, if I add a new repo in my GitHub account, I'd need to remember to update this list.
So I'm opening this issue to suggest a configuration interface change. Instead of the list of repos and the option `include_all_repos`, it could instead have two lists: `include_repos` and `exclude_repos`.
- If you have listed repos in `include_repos`, this would mean include ONLY the listed ones.
- If you have listed `exclude_repos`, this would mean sync all repos EXCEPT those listed.
- If both lists are empty, that would mean sync ALL repos.
- And if both lists have items, that's an invalid state and could be an error or the program could prioritize one of the lists and ignore the other.

This interface would allow with the same number of properties, to express filters more easily.

Tell me what you think 😊

**Comment by AkashRajpurohit** [comment]
This seems like a good addition, and the scenario described is definitely a painful one.

We can pick this up, do you want to send a PR for adding this? @jbonadiman 

I can take a look over this weekend if I get sometime or if you want to take it up then feel free to do it, I'll review it.

**Comment by AkashRajpurohit** [comment]
@jbonadiman the new release [v0.2.0](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.2.0) adds this feature, it's a breaking change so the config needs to be updated accordingly and details are mentioned in the README, if you give it a try and see any issues then do report it back. Thanks for opening this feature request!
