### ISSUE TITLE
feature request: auto retry + skip

### ISSUE THREAD

**Issue by ImSingee** [AkashRajpurohit/git-sync#76]
### Describe the feature or enhancement

Now, if cloning of any repo fails, the program exits immediately.

Sometimes, this is a permission problem, and sometimes a temporary network issue or rate limit error.

I hope if there's an error occurs, it should be auto-retry for some time (to prevent temporary error), and if it's still error after the maximum retry time, simply skip it and handle next repo (not exit the whole program).

**Comment by AkashRajpurohit** [comment]
makes sense, thanks for the sharing the suggestion.

**Comment by AkashRajpurohit** [comment]
Additionally, if you want to contribute with this feature then feel free to pick it up! :)

**Comment by ImSingee** [comment]
@AkashRajpurohit Got it. Since the project is new for me, I don’t have enough time to work on it now. But I may take it next week if I have free time then.

**Comment by AkashRajpurohit** [comment]
@ImSingee this feature have been landed in the latest [0.15.0](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.15.0) release. It was quite fun working on this, thanks for the sharing about this, do try it and let me know if you face any issues.

**Comment by ImSingee** [comment]
@AkashRajpurohit Thanks for implementing my request feature!

BTW, I belive there must be a problem related the retry:

https://github.com/AkashRajpurohit/git-sync/blob/9ebbaf694c069904d3a5c9e0db9b74a601e8b308/pkg/sync/sync.go#L79

The `command` is reused between the retry. But it can't -- the second (and later) call to `CombinedOutput` will fail as Golang expect each command to be only used once and it will return a "stdout is already set" error (https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/os/exec/exec.go;l=1013). 

I don't have a computer with golang setup now. I will submit the PR tomorrow (but if you have time, feel free to fix it by yourself).

**Comment by AkashRajpurohit** [comment]
Nice catch, thanks for pointing this out.
I've pushed [this commit](https://github.com/AkashRajpurohit/git-sync/commit/e2e95e95c2e0cffa73ad152c4084ef051fac0dae) to address this, let me know if you have any thoughts on this. Will create a patch release on 0.15 with this fix.

**Comment by AkashRajpurohit** [comment]
@all-contributors please add @ImSingee for ideas.
